### ISSUE TITLE
Error on "using ONSAS.DynamicState"

### ISSUE THREAD

**Issue by tkrisnguyen** [mvanzulli/ONSAS.jl#491]
Hello,

I just rerun [dynamic_analyses.jl](https://github.com/ONSAS/ONSAS.jl/blob/main/test/structural_analyses/dynamic_analyses.jl), but with the command

using ONSAS.DynamicStates

the following error appear:

ERROR: UndefVarError: `DynamicStates` not defined

How can I resolve this problem?

Thank you.

**Comment by mvanzulli** [comment]
Hey there, currently dynamic analysis is not supported. We have issues to start address this according to ONSAS.m implementation. Im happy to have a quick chat if you are keen.

**Comment by tkrisnguyen** [comment]
I'm happy to involve in (solving) this issue.

**Comment by mvanzulli** [comment]
Thank you so much for your motivation. I think currently we are not planning to extend the capabilities of this package to solve dynamic analysis. You can use [ONSAS.m](https://github.com/ONSAS/ONSAS) which is validated and has multiple algorithms to solve dynamic analysis. 


Regarding the issue, can you provide the code to reproduce the issue. If a execute `julia --project test/structural_analyses/dynamic_analyses.jl` form ONSAS root folder then works fine. Seems that you are trying to use the REPL, since ONSAS exports `DynamicStates` modules `@reexport using .DynamicStates` make sure you have instantiated the ONSAS environemnt `julia --project=.` from the root.

**Comment by mvanzulli** [comment]
If you want, you can submit an MR adding the following comment in `dynamic_analysis.jl`  and `DynamicStates` if that helps: 
```julia
"""
WARNING: These test files are placeholders for future development of Dynamic Analysis in ONSAS.jl but are not currently supported.
"""
```

**Comment by tkrisnguyen** [comment]
What is "an MR"? I am sorry for this newbee question.

**Comment by mvanzulli** [comment]
Oh sorry I didn't clarify that in the first place. I meant a [pull request](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request). But is just optional if you want to contribute just adding this comment into the files. Since this is not an issue I think we can close it :)
